# переменная для Value c сообщением для контроллера
app:
  message: message successfully sent

# настройки RabbitMQ
spring:
  rabbitmq:
    host: rabbitmq # было localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    routingkey: user.routingkey

server:
  port: 8081

# Примечание 1
# в файле docker-compose.yml мы назначаем сервису rabbitmq
# hostname: rabbitmq, а здесь к нему обращаемся по этому имени