# переменная для Value c сообщением для контроллера
app:
  message: message successfully sent

# настройки RabbitMQ
producer:
  rabbitmq:
    host: rabbitmq # было localhost
    virtual_host: /
    password: guest
    username: guest
    port: 5672
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

server:
  port: 8081

# Примечание 1
# в файле docker-compose.yml мы назначаем сервису rabbitmq
# hostname: rabbitmq, а здесь к нему обращаемся по этому имени

# Примечание 2 (о портах)
# по умолчанию порт: 5672 для amqp, 15672 - для управления

# Примечание 3
# Настройки RabbitMQ делаем с разным префиксом (producer, consumer)
# на тот случай, если возникут ошибки, будет понятно из какого сервиса